### ISSUE TITLE
Another checkpointing bug with new-style checkpointing

### ISSUE THREAD

**Issue by epwalsh** [allenai/OLMo#312]
This was reported a while ago but still isn't fixed: https://github.com/pytorch/pytorch/issues/102821

Here's our own stacktrace for completeness. Rank 0:

```
2023-10-04 21:33:46.745 inst-agzdq-r12z3-workers:0      olmo.util:133   CRITICAL        Uncaught RuntimeError: Invalid function argument. Expected parameter `scatter_list` to be of type List[torch.Tensor].
Traceback (most recent call last):
  File "/LLM/scripts/train.py", line 249, in <module>
    main(cfg)
  File "/LLM/scripts/train.py", line 213, in main
    trainer.restore_checkpoint(cfg.load_path)
  File "/LLM/olmo/train.py", line 565, in restore_checkpoint
    self.restore_sharded_checkpoint(load_path, local_cache=local_cache)
  File "/LLM/olmo/train.py", line 345, in restore_sharded_checkpoint
    load_fsdp_model_and_optim_state(load_path, self.fsdp_model, self.optim, local_cache=local_cache)
  File "/LLM/olmo/checkpoint.py", line 139, in load_fsdp_model_and_optim_state
    optim_state = load_sharded_optimizer_state_dict(
  File "/usr/lib/python3/dist-packages/torch/distributed/checkpoint/optimizer.py", line 282, in load_sharded_optimizer_state_dict
    state_dict[key] = _shard_tensor(
  File "/usr/lib/python3/dist-packages/torch/distributed/_shard/api.py", line 70, in _shard_tensor
    st = sharding_spec.shard(tensor, src_rank=src_rank, process_group=process_group)
  File "/usr/lib/python3/dist-packages/torch/distributed/_shard/sharding_spec/chunk_sharding_spec.py", line 181, in shard
    dist.scatter(
  File "/usr/lib/python3/dist-packages/torch/distributed/distributed_c10d.py", line 1451, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/torch/distributed/distributed_c10d.py", line 2774, in scatter
    _check_tensor_list(scatter_list, "scatter_list")
  File "/usr/lib/python3/dist-packages/torch/distributed/distributed_c10d.py", line 599, in _check_tensor_list
    raise RuntimeError(
RuntimeError: Invalid function argument. Expected parameter `scatter_list` to be of type List[torch.Tensor].
```

At least one other rank will fail with an assertion error: `assert local_tensor is not None`.

I believe this happens when part of the model is only sharded across a strict subset of all ranks, which is often the case for us with our current FSDP settings.

I have an idea for a fix that I'm working on now.

**Comment by dumitrac** [comment]
Marking the items prior to Feb 29th as "closed".
