### ISSUE TITLE
cannot import name 'OLMoConfig' from partially initialized module 'hf_olmo' (most likely due to a circular import)

### ISSUE THREAD

**Issue by OliverXUZY** [allenai/OLMo#473]
### 🐛 Describe the bug

Hi,
  Thanks for the great work! When i run the example code below:
```
from hf_olmo import * # registers the Auto* classes

from transformers import AutoModelForCausalLM, AutoTokenizer

olmo = AutoModelForCausalLM.from_pretrained("allenai/OLMo-7B")
tokenizer = AutoTokenizer.from_pretrained("allenai/OLMo-7B")

message = ["Language modeling is "]
inputs = tokenizer(message, return_tensors='pt', return_token_type_ids=False)
response = olmo.generate(**inputs, max_new_tokens=100, do_sample=True, top_k=50, top_p=0.95)
print(tokenizer.batch_decode(response, skip_special_tokens=True)[0])
```
I got an error due to `circular import`.

```
Traceback (most recent call last):
  File "/srv/home/zxu444/browse/com_icl/debug/olmo.py", line 1, in <module>
    from hf_olmo import * # registers the Auto* classes
    ^^^^^^^^^^^^^^^^^^^^^
  File "/srv/home/zxu444/anaconda3/envs/llm/lib/python3.11/site-packages/hf_olmo/__init__.py", line 1, in <module>
    from .configuration_olmo import OLMoConfig
  File "/srv/home/zxu444/anaconda3/envs/llm/lib/python3.11/site-packages/hf_olmo/configuration_olmo.py", line 8, in <module>
    from olmo.config import ModelConfig
  File "/srv/home/zxu444/browse/com_icl/debug/olmo.py", line 5, in <module>
    olmo = AutoModelForCausalLM.from_pretrained("allenai/OLMo-7B",trust_remote_code=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/home/zxu444/anaconda3/envs/llm/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 521, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/home/zxu444/anaconda3/envs/llm/lib/python3.11/site-packages/transformers/models/auto/configuration_auto.py", line 1120, in from_pretrained
    config_class = get_class_from_dynamic_module(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/home/zxu444/anaconda3/envs/llm/lib/python3.11/site-packages/transformers/dynamic_module_utils.py", line 500, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/home/zxu444/anaconda3/envs/llm/lib/python3.11/site-packages/transformers/dynamic_module_utils.py", line 200, in get_class_in_module
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/home/zxu444/anaconda3/envs/llm/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/home/zxu444/.cache/huggingface/modules/transformers_modules/allenai/OLMo-7B/09dd55d8d37c14aa0cbab5a4ac545140d2bd0a60/configuration_olmo.py", line 1, in <module>
    from hf_olmo import OLMoConfig
ImportError: cannot import name 'OLMoConfig' from partially initialized module 'hf_olmo' (most likely due to a circular import) (/srv/home/zxu444/anaconda3/envs/llm/lib/python3.11/site-packages/hf_olmo/__init__.py)


```

Any guidance is appreciated! Thank you!

### Versions

i paste my version below:

```
Python 3.11.8
ai2-olmo==0.2.4
antlr4-python3-runtime==4.9.3
boto3==1.34.52
botocore==1.34.52
cached_path==1.6.0
cachetools==5.3.3
certifi==2024.2.2
charset-normalizer==3.3.2
filelock==3.13.1
fsspec==2024.2.0
google-api-core==2.17.1
google-auth==2.28.1
google-cloud-core==2.4.1
google-cloud-storage==2.14.0
google-crc32c==1.5.0
google-resumable-media==2.7.0
googleapis-common-protos==1.62.0
huggingface-hub==0.20.3
idna==3.6
Jinja2==3.1.3
jmespath==1.0.1
markdown-it-py==3.0.0
MarkupSafe==2.1.5
mdurl==0.1.2
mpmath==1.3.0
networkx==3.2.1
numpy==1.26.4
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.18.1
nvidia-nvjitlink-cu12==12.3.101
nvidia-nvtx-cu12==12.1.105
omegaconf==2.3.0
packaging==23.2
protobuf==4.25.3
pyasn1==0.5.1
pyasn1-modules==0.3.0
Pygments==2.17.2
python-dateutil==2.8.2
PyYAML==6.0.1
regex==2023.12.25
requests==2.31.0
rich==13.7.1
rsa==4.9
s3transfer==0.10.0
safetensors==0.4.2
six==1.16.0
sympy==1.12
tokenizers==0.15.2
torch==2.1.2
tqdm==4.66.2
transformers==4.38.1
triton==2.1.0
typing_extensions==4.10.0
urllib3==2.0.7

```

**Comment by epwalsh** [comment]
@OliverXUZY it looks like you have a file called `/srv/home/zxu444/browse/com_icl/debug/olmo.py`, which conflicts with the `olmo` package. That might be the issue.

**Comment by OliverXUZY** [comment]
Yes this is the issue, thank you for pointing this out!
