### ISSUE TITLE
olmo-torch2-base does not exist in docker hub

### ISSUE THREAD

**Issue by Arvin-Hu** [allenai/OLMo#496]
### 📚 The doc issue

In [OLMo](https://github.com/allenai/OLMo/tree/main)
/docker, line 7: FROM olmo-torch2-base

The olmo-torch2-base does not exist in the docker hub and is not accessible through the Internet (which means a 404 error for https://hub.docker.com/search?q=olmo-torch2-base). Is there an updated address for this olmo-torch2-base image?

**Comment by 2015aroras** [comment]
Hi, could you please share what you ran to come across this issue?

**Comment by Arvin-Hu** [comment]
Hi, here is what I come across. I can not build an image from file docker/Dockerfile.gantry. 

To have an image built by the file in docker/Dockerfile.gantry, we need first to build a olmo-torch2-base image using docker/Dockerfile.base. 

I have an image  olmo-torch2-base :v1 built using  docker/Dockerfile.base through the following command (inside the docker folder)

docker build -f Dockerfile.base -t olmo-torch2-base :v1  . --network=host

Then I proceed to build  (inside the main OLMo folder)

docker build -f docker/Dockerfile.gantry1 -t olmo-torch2-gantry :v1 . --network=host

where Dockerfile.gantry1 is the same as Dockerfile.gantry in the docker folder except that the base image is changed to olmo-torch2-base :v1 as following
```
FROM olmo-torch2-gantry :v1

WORKDIR /stage

COPY pyproject.toml .
RUN mkdir olmo && touch olmo/__init__.py && \
    pip install --no-cache-dir .[all] && \
    pip uninstall -y ai2-olmo && \
    rm -rf olmo/

WORKDIR /app/olmo
```
But I get an error saying that ModuleNotFoundError: No module named 'olmo'. The details are 

$ docker build -f docker/Dockerfile.gantry1 -t llmcourse:gantry1 . --network=host   
            
[+] Building 15.0s (8/9)                                                 
 => [internal] load .dockerignore                                                                                                                                                                                                                                                                0.0s
 => => transferring context: 108B                                                                                                                                                                                                                                                                0.0s
 => [internal] load build definition from Dockerfile.gantry1                                                                                                                                                                                                                                     0.0s
 => => transferring dockerfile: 535B                                                                                                                                                                                                                                                             0.0s
 => [internal] load metadata for docker.io/library/olmo-torch2-gantry :v1                                                                                                                                                                                                                               0.0s
 => [1/5] FROM docker.io/library/olmo-torch2-gantry :v1                                                                                                                                                                                                                                             0.0s
 => [internal] load build context                                                                                                                                                                                                                                                                0.0s
 => => transferring context: 36B                                                                                                                                                                                                                                                                 0.0s
 => CACHED [2/5] WORKDIR /stage                                                                                                                                                                                                                                                                  0.0s
 => CACHED [3/5] COPY pyproject.toml .                                                                                                                                                                                                                                                           0.0s
 => ERROR [4/5] RUN mkdir olmo && touch olmo/__init__.py &&     pip install --no-cache-dir .[all] &&     pip uninstall -y ai2-olmo &&     rm -rf olmo/                                                                                                                                          15.0s
------                                                                   
 > [4/5] RUN mkdir olmo && touch olmo/__init__.py &&     pip install --no-cache-dir .[all] &&     pip uninstall -y ai2-olmo &&     rm -rf olmo/:   
#0 10.89 Processing /stage                                                                                                                                                                                                                                                                            
#0 10.90   Installing build dependencies: started                                                                                                                                                                                                                                                     
#0 14.25   Installing build dependencies: finished with status 'done'                                                                                                                                                                                                                                 
#0 14.25   Getting requirements to build wheel: started                                                                                                                                                                                                                                               
#0 14.53   Getting requirements to build wheel: finished with status 'error'                                                            
#0 14.55   error: subprocess-exited-with-error           
#0 14.55                                                   
#0 14.55   × Getting requirements to build wheel did not run successfully.                                                                                                                                                                                                                            
#0 14.55   │ exit code: 1         
#0 14.55   ╰─> [43 lines of output]
#0 14.55       Traceback (most recent call last):                                                                                                                                                                                                                                                     
#0 14.55         File "/opt/conda/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
#0 14.55           main()
#0 14.55         File "/opt/conda/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
#0 14.55           json_out['return_val'] = hook(**hook_input['kwargs'])
#0 14.55         File "/opt/conda/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
#0 14.55           return hook(config_settings)
#0 14.55         File "/tmp/pip-build-env-khvh7t8h/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
#0 14.55           return self._get_build_requires(config_settings, requirements=['wheel'])
#0 14.55         File "/tmp/pip-build-env-khvh7t8h/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires 
#0 14.55           self.run_setup()
#0 14.55         File "/tmp/pip-build-env-khvh7t8h/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
#0 14.55           exec(code, locals())
#0 14.55         File "<string>", line 1, in <module>
#0 14.55         File "/tmp/pip-build-env-khvh7t8h/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 104, in setup
#0 14.55           return distutils.core.setup(**attrs)
#0 14.55         File "/tmp/pip-build-env-khvh7t8h/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 159, in setup
#0 14.55           dist.parse_config_files()
#0 14.55         File "/tmp/pip-build-env-khvh7t8h/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 631, in parse_config_files
#0 14.55           pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
#0 14.55         File "/tmp/pip-build-env-khvh7t8h/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 68, in apply_configuration
#0 14.55           config = read_configuration(filepath, True, ignore_option_errors, dist)
#0 14.55         File "/tmp/pip-build-env-khvh7t8h/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 133, in read_configuration
#0 14.55           return expand_configuration(asdict, root_dir, ignore_option_errors, dist)
#0 14.55         File "/tmp/pip-build-env-khvh7t8h/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 158, in expand_configuration
#0 14.55           return _ConfigExpander(config, root_dir, ignore_option_errors, dist).expand()
#0 14.55         File "/tmp/pip-build-env-khvh7t8h/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 206, in expand
#0 14.55           self._expand_all_dynamic(dist, package_dir)
#0 14.55         File "/tmp/pip-build-env-khvh7t8h/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 251, in _expand_all_dynamic
#0 14.55           version=self._obtain_version(dist, package_dir),
#0 14.55         File "/tmp/pip-build-env-khvh7t8h/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 300, in _obtain_version
#0 14.55           return _expand.version(self._obtain(dist, "version", package_dir))
#0 14.55         File "/tmp/pip-build-env-khvh7t8h/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 289, in _obtain
#0 14.55           return self._expand_directive(
#0 14.55         File "/tmp/pip-build-env-khvh7t8h/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 283, in _expand_directive
#0 14.55           return _expand.read_attr(directive["attr"], package_dir, root_dir)
#0 14.55         File "/tmp/pip-build-env-khvh7t8h/overlay/lib/python3.10/site-packages/setuptools/config/expand.py", line 189, in read_attr
#0 14.55           spec = _find_spec(module_name, path)
#0 14.55         File "/tmp/pip-build-env-khvh7t8h/overlay/lib/python3.10/site-packages/setuptools/config/expand.py", line 201, in _find_spec
#0 14.55           spec = spec or importlib.util.find_spec(module_name)
#0 14.55         File "/opt/conda/lib/python3.10/importlib/util.py", line 94, in find_spec
#0 14.55           parent = __import__(parent_name, fromlist=['__path__'])
#0 14.55       ModuleNotFoundError: No module named 'olmo'
#0 14.55       [end of output]
#0 14.55   
#0 14.55   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 14.56 error: subprocess-exited-with-error
#0 14.56 
#0 14.56 × Getting requirements to build wheel did not run successfully.
#0 14.56 │ exit code: 1
#0 14.56 ╰─> See above for output.
#0 14.56 
#0 14.56 note: This error originates from a subprocess, and is likely not a problem with pip.
------
Dockerfile.gantry1:13
--------------------
  12 |     COPY pyproject.toml .
  13 | >>> RUN mkdir olmo && touch olmo/__init__.py && \
  14 | >>>     pip install --no-cache-dir .[all] && \
  15 | >>>     pip uninstall -y ai2-olmo && \
  16 | >>>     rm -rf olmo/
  17 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c mkdir olmo && touch olmo/__init__.py &&     pip install --no-cache-dir .[all] &&     pip uninstall -y ai2-olmo &&     rm -rf olmo/" did not complete successfully: exit code: 1
